name: starbooks

services:
  flutter-web:
    image: dostnexus/flutter-starbooks:latest
    container_name: flutter-starbooks
    ports:
      - "8080:80"
    networks:
      - starbooks-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-api
    networks:
      - starbooks-network

  laravel-api:
    image: dostnexus/laravel-starbooks-api:latest
    container_name: laravel-starbooks
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=starbooksWhizbee
      - MONGODB_URI=mongodb://mongodb:27017 
    depends_on:
      - mongodb
    networks:
      - starbooks-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-starbooks
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=starbooksWhizbee
    networks:
      - starbooks-network
  
  battle-server:
    image: dostnexus/whiz-battle-server:latest
    container_name: battle-server
    ports:
      - "8085:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - LARAVEL_API_URL=http://nginx:80/api
    depends_on:
      - mongodb
      - nginx
    networks:
      - starbooks-network

networks:
  starbooks-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local