name: starbooks

services:
  flutter-web:
    image: dostnexus/flutter-starbooks:latest
    container_name: flutter-starbooks
    ports:
      - "8080:80"
    networks:
      - starbooks-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-api
    networks:
      - starbooks-network

  laravel-api:
    image: dostnexus/laravel-starbooks-api:latest
    container_name: laravel-starbooks
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=starbooksWhizbee
      - MONGODB_URI=mongodb://mongodb:27017
      - APP_KEY=base64:YK96P6FCOjs3UeHff6yip09Badf7krdeL9ng7yM6uLo=
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - starbooks-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-starbooks
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=starbooksWhizbee
    networks:
      - starbooks-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  battle-server:
    image: dostnexus/whiz-battle-server:latest
    container_name: battle-server
    ports:
      - "8085:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - LARAVEL_API_URL=http://nginx:80/api
    depends_on:
      mongodb:
        condition: service_healthy
      nginx:
        condition: service_started
    networks:
      - starbooks-network

networks:
  starbooks-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local